// app/src/models/address.model.ts

/**
 * address model
 * -----------------
 * This file defines the Sequelize `Address` model, which represents the `addresses` table in the database.
 *
 * It contains:
 * - Model attributes (`AddressAttributes`).
 * - Required attributes for creation (`AddressCreationAttributes`).
 * - Definition of the model with its columns and constraints.
 *
 * This model is used by services and controllers to perform CRUD operations.
 */
import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Attributes for `Address`.
 */
export interface AddressAttributes {
    id_address: number;
    country: string;
    department: string;
    city: string;
    postal_code: string;
    street: string;
    number: string;
    is_active: boolean;
}

/**
 * Attributes used for creating a new address.
 * `Optional` is used to indicate that `id` is not required at the time
 * of creation, as it is automatically generated by the database.
 */
export interface AddressCreationAttributes extends Optional<AddressAttributes, "id_address"> { }

/**
 * Class that represents the `Address` model in Sequelize.
 *
 * Implements the attributes defined in `AddressAttributes` and `AddressCreationAttributes`.
 */
class Address extends Model<AddressAttributes, AddressCreationAttributes> implements AddressAttributes {

    public id_address!: number;
    public country!: string;
    public department!: string;
    public city!: string;   
    public postal_code!: string;
    public street!: string;
    public number!: string;
    public is_active!: boolean;
}

/**
 * Initialization of the `Address` model with Sequelize configuration.
 *
 * - `id_address`: Auto-incrementing integer, primary key.
 * - `country`: Foreign key referencing the country of the address.
 * - `departament_id`: Foreign key referencing the department of the address.
 * - `city`: Foreign key referencing the city of the address.
 * - `postal_code`: String representing the postal code.
 * - `street`: String representing the street name.
 * - `number`: String representing the street number.
 * - `is_active`: Boolean to determine if the address is active or inactive.
 */
Address.init(
    {
        id_address: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        country: {
            type: DataTypes.STRING(100),
            allowNull: false
        },
        department: {
            type: DataTypes.STRING(100),
            allowNull: false
        },
        city: {
            type: DataTypes.STRING(100),
            allowNull: false
        },
        postal_code: {
            type: DataTypes.STRING(20),
            allowNull: false
        },
        street: {
            type: DataTypes.STRING(100),
            allowNull: false,
        },
        number: {
            type: DataTypes.STRING(20),
            allowNull: false,
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "Address",   
        tableName: "address",  // Singular para consistencia
        timestamps: true,      
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default Address;
