// app/src/models/customer.model.ts

/**
 * Customer Model
 * -----------------
 * This file defines the Sequelize `customer` model, which represents the `customers` table in the database.
 * 
 * It contains:
 * - Model attributes (`customerAttributes`).
 * - Attributes required for creation (`customerCreationAttributes`).
 * - Model definition with its columns and constraints.
 * 
 * This model is used by services and controllers to perform CRUD operations.
 */

import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the `customer` entity.
 */
export interface CustomerAttributes {
  id_customer: number;
  address_id: number;
  fullname: string;
  email: string;
  is_active: boolean;
}

/**
 * Attributes used for creating a new customer.
 * 
 * `Optional` is used to indicate that `id_customer` is not required at the time of creation, as it is automatically generated by the database.
 */
export interface CustomerCreationAttributes extends Optional<CustomerAttributes, "id_customer" > {}

/**
 * Class that represents the `customer` model in Sequelize.
 * 
 * Implements the attributes defined in `customerAttributes` and `customerCreationAttributes`.
 */
class Customer extends Model<CustomerAttributes, CustomerCreationAttributes> implements CustomerAttributes {
  /** Unique customer identifier (primary key). */
  public id_customer!: number;
  
  /** customer access identifier (foreign key). */
  public address_id!: number;
  

  /** Full name of the customer's customername. */
  public fullname!: string;
  
  /** customer's phone number. */
  public phone!: string | null;

  /** Unique email address of the customer. */
  public email!: string;

  /** State in which the customer is (active/inactive) */
  public is_active!: boolean;
}

/**
 * Initialization of the `customer` model with the Sequelize configuration.
 * 
 * - `id_customer`: Auto-incrementing integer, primary key.
 * - `access_id`: Integer, foreign key.
 * - `gender_id`: Integer, foreign key.
 * - `fullname`: customer's full name, with a maximum of 100 characters.
 * - `email`: A unique and mandatory email address, with a maximum of 100 characters.
 * - `birth_date`: customer's birthday.
 * - `phone`: customer's phone number, with a maximum of 20 characters.
 * - `is_active`: A Boolean to determine whether the customer is active or inactive.
 */
Customer.init(
  {
    id_customer: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    address_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "address",
        key: "id_address",
      },
    },

    fullname: {
      type: DataTypes.STRING(100),
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING(100),
      unique: true,
      allowNull: false,
    },
    is_active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
    }
  },
  {
    sequelize,
    modelName: "Customer",      // Model name in Sequelize
    tableName: "customer",    // Name of the table in the database (singular)
    timestamps: true,      // includes createdAt and updatedAt
    createdAt: "created_at",
    updatedAt: "updated_at"
  }
);

export default Customer;
