// app/src/models/orderItem.model.ts

/**
/**
 * OrderItem Model
 * ----------
 * This file defines the Sequelize `OrderItem` model, which represents the `order_items` table in the database.
 *
 * 
 * Contains:
 *  - Model attributes (`OrderItemAttributes`).
 *  - Required attributes for creation (`OrderItemCreationAttributes`).
 *  - Model definition with its columns and constraints.
 * 
 * This model is used by services and controllers to perform CRUD operations.
 */


import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 *  Main attributes of the `OrderItem` entity.
 */
export interface OrderItemAttributes {
    id_order_item: number;
    product_id:number;
    order_id: number;
    quantity: number;
    is_active: boolean;
}

/**
 * Attributes used for creating a new order_item.
 * `Optional` is used to indicate that `id` is not required at the time
 * of creation, as it is automatically generated by the database.
 */

export interface OrderItemCreationAttributes extends Optional<OrderItemAttributes, "id_order_item"> { }


/**
 * Class that represents the `order_item` model in Sequelize.
 * 
 * Implements the attributes defined in `OrderItemAttributes` and `ProductsCreationAttributes`.
 */
class OrderItem extends Model<OrderItemAttributes, OrderItemCreationAttributes> implements OrderItemAttributes {
    public id_order_item!: number;
    public order_id!: number;
    public product_id!: number;
    public quantity!: number;
    public is_active!: boolean;
}


/**

 * 
 * Properties include:
 * - `id_order_item`: Primary key, unique identifier for each order item.
 * - `order_id`: Foreign key linking to the related order.
 * - `product_id:  Foreign key linking to the related Product
 * - `quantity: quantity of the order items
 * - `is_active`: Boolean flag to indicate if the order item is active or inactive.
 * 
 * This class serves as the blueprint for CRUD operations on order items within the database.
 */


OrderItem.init(
    {
        id_order_item: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        order_id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: "order",
                key: "id_order",
            }
        },
        product_id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: "product",
                key: "id_product",
            }
        },
        quantity: {
            type: DataTypes.INTEGER,
            allowNull: false
        },
        is_active:{
            type: DataTypes.BOOLEAN,
            allowNull: false,
        }
    },
    {
        sequelize,
        modelName: "OrderItem",      // Name of the model in Sequelize
        tableName: "order_item",    // Name of the table in the database (singular)
        timestamps: true,       // includes createdAt and updatedAt
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default OrderItem;
