/**
 * Order Model
 * -----------------
 * This file defines the Sequelize `Order` model, which represents the `orders` table in the database..
 * 
 * Contains:
 *  - model atributes (`OrderAttributes`).
 *  - Attributes required for creation (`OrderCreationAttributes`).
 *  - Defining the model with its columns and restrictions.
 * 
 * This model is used by services and controllers to perform CRUD operations..
 */

import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the entity `Order`.
 */
export interface OrderAttributes {
  id_order: number;
  customer_id: number;
  order_status_id: number;
  warehouse_id: number;
  is_active: boolean;
}

/**
 * Attributes used for the creation of a new Order.
 * 
 * `Optional` is used to indicate that `id_order` is not currently required.
 * of creation, since it is automatically generated by the database.
 */
export interface OrderCreationAttributes extends Optional<OrderAttributes, "id_order" > {}

/**
 * Class that represents the `Order` model in Sequelize.
 * 
 * Implements the attributes defined in `OrderAttributes` and `OrderCreationAttributes`.
 */
class Order extends Model<OrderAttributes, OrderCreationAttributes> implements OrderAttributes {
  public id_order!: number;
  public customer_id!: number;
  public order_status_id!: number;
  public warehouse_id!: number;
  public is_active!: boolean;

}

/**
 * Initializing the `Order` model with Sequelize configuration.
 * 
 * - `id_order`: Auto-incrementing integer, primary key.
 * - `customer_id`: Foreign key referencing the `customers` table.
 * - `order_status_id`: Foreign key referencing the `order_status` table.
 * - `warehouse_id`: Foreign key referencing the `warehouses` table.
 * - `is_active`: Boolean to determine whether the Order is active or inactive.
 */
Order.init(
  {
    id_order: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    customer_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "customer",
        key: "id_customer",
      }
    },
     order_status_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "order_status",
        key: "id_order_status",
        }
    },
    warehouse_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references:{
        model: "warehouses",
        key: "id_warehouse",
      }
    },
    is_active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
    }
  },

  {
    sequelize,
    modelName: "Order",      // Model name in Sequelize
    tableName: "order",    // Name of the table in the database (singular)
    timestamps: true,      // includes createdAt and updatedAt
    createdAt: "created_at",
    updatedAt: "updated_at"
  }
);

export default Order;
