// app/src/models/orderStatus.model.ts

/**
 * Order Status Model
 * -----------------
 * This file defines the Sequelize  `OrderStatus` model, which represents the  order_status` table in the database.
 *
 * Contains:
 *  - Model attributes ( `OrderStatusAttributes`).
 *  - Required attributes for creation ( `OrderStatusCreationAttributes`).
 *  - Model definition with its columns and constraints.
 *
 * This model is used by the services and controllers to perform CRUD operations.
 */
import { DataTypes,Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the `Order status` entity.
 */

export interface OrderStatusAttributes {
    id_order_status : number;
    name : string;
}

/**
 * Attributes used for creating a new Order status.
 * `Optional` is used to indicate that `id` is not required at the time
 * of creation, since it is automatically generated by the database.
 */

export interface OrderStatusCreationAttributes extends Optional<OrderStatusAttributes, "id_order_status"> { }

/**
 * Class that represents the `Order Status` model in Sequelize.
 * 
 * Implements the attributes defined in  `OrderStatusAttributes` and  OrderStatusCreationAttributes`.
 */
class OrderStatus extends Model<OrderStatusAttributes, OrderStatusCreationAttributes> implements OrderStatusAttributes { 
    public id_order_status!: number;
    public name!: string;
}

/**
 * Initialization of the `Order Status` model with Sequelize configuration.
 * 
 * - `id_order_status`: Auto-increment integer, primary key.
 * - `name`: status of order (delivered, in transit, pending).
 * - `is_active`: Boolean to determine whether the account is active or inactive.
 */
OrderStatus.init(
    {
        id_order_status:{
            type:DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        name:{
            type: DataTypes.STRING(100),
            unique: true,
            allowNull: false,
        },
    },
    {
        sequelize,
        modelName: "OrderStatus", //Name of model in Sequelize
        tableName: "order_status",  // Name of table in the database (singular)
        timestamps : true, // Include createdAt and updatedAt
        createdAt : "created_at",
        updatedAt : "updated_at"
    }
)

export default OrderStatus;